const newsTypes = {
  COUNTRY_SWITCH: 'COUNTRY_SWITCH',
  COUNTRY_SWITCHER_STATE: 'COUNTRY_SWITCHER_STATE',

  FETCH_TOP_NEWS: 'FETCH_TOP_NEWS',
  FETCH_TOP_NEWS_SUCCESS: 'FETCH_TOP_NEWS_SUCCESS',
  FETCH_TOP_NEWS_FAIL: 'FETCH_TOP_NEWS_FAIL',
};

export default newsTypes;
