const newsTypes = {
  COUNTRY_SWITCH: 'COUNTRY_SWITCH',
  COUNTRY_SWITCHER_STATE: 'COUNTRY_SWITCHER_STATE',

  FETCH_TOP_NEWS: 'FETCH_TOP_NEWS',
  FETCH_TOP_NEWS_SUCCESS: 'FETCH_TOP_NEWS_SUCCESS',
  FETCH_TOP_NEWS_FAIL: 'FETCH_TOP_NEWS_FAIL',

  FETCH_TOP_NEWS_BY_CATEGORY: 'FETCH_TOP_NEWS_BY_CATEGORY',
  FETCH_TOP_NEWS_BY_CATEGORY_SUCCESS: 'FETCH_TOP_NEWS_BY_CATEGORY_SUCCESS',
  FETCH_TOP_NEWS_BY_CATEGORY_FAIL: 'FETCH_TOP_NEWS_BY_CATEGORY_FAIL',

  FETCH_TOP_NEWS_BY_TERM: 'FETCH_TOP_NEWS_BY_TERM',
  FETCH_TOP_NEWS_BY_TERM_SUCCESS: 'FETCH_TOP_NEWS_BY_TERM_SUCCESS',
  FETCH_TOP_NEWS_BY_TERM_FAIL: 'FETCH_TOP_NEWS_BY_TERM_FAIL',
};
export default newsTypes;
